export const SET_USER = "SET_USER";
export const SET_USER_AUTHENTICATED = "SET_USER_AUTHENTICATED";
export const SEARCH_TYPING = "SEARCH_TYPING";
export const FORM_INPUT_CHANGE = "FORM_INPUT_CHANGE";
export const FORM_SUBMIT = "FORM_SUBMIT_HANLDER";
export const FORM_INPUT_ERROR = "FORM_INPUT_ERROR";
export const FORM_INPUT_ERRORS = "FORM_INPUT_ERRORS";
export const FORM_INPUT_VALID = "FORM_INPUT_VALID";
